apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: nw1l4m4vd-nodejs 
  janus-idp.io/tekton: nw1l4m4vd-nodejs
  backstage.io/kubernetes-id: nw1l4m4vd-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: nw1l4m4vd-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml